import csv
import os

# Create directory if it doesn't exist
os.makedirs(os.path.dirname(__file__), exist_ok=True)

data = [
    # TECH
    ("Introduction to React 19 and its new features", 
     "React 19 brings React Server Components, Actions API, and the new compiler.", 
     "React 19 is a major release. It introduces the React Compiler which optimizes re-renders automatically. We also get new Hooks like useActionState and useFormStatus for handling forms, alongside first-class support for async transitions.", 
     "Tech"),
    ("Understanding Python Decorators and generators", 
     "Learn how decorators and generators work in Python with concrete examples.", 
     "Decorators are a powerful way to modify the behavior of functions or classes. They allow you to wrap another function to extend its behavior without modifying it. Generators allow you to declare a function that behaves like an iterator, yielding values one by one.", 
     "Tech"),
    ("Why you should use Git branch workflows in team projects", 
     "Best practices for Git branch management in modern development teams.", 
     "Git branch workflows like Git Flow or GitHub Flow are essential for software engineering teams. They allow multiple developers to work on features independently without messing up the main branch. Always create a feature branch, run tests, and open a pull request before merging to main.", 
     "Tech"),
    ("How to design REST APIs using Django REST Framework", 
     "A step-by-step guide to building scalable endpoints with DRF.", 
     "Django REST Framework is the standard for building RESTful APIs in Python. It provides powerful serialization, built-in authentication using JWT, and customizable permissions. By leveraging ViewSets and Routers, you can set up CRUD endpoints quickly and securely.", 
     "Tech"),
    ("Docker containers vs Virtual Machines: the key differences", 
     "An analysis of containerization vs virtualization architectures.", 
     "Docker containers share the host operating system kernel, making them lightweight, fast, and resource-efficient. Virtual machines, on the other hand, run a full guest operating system, which adds overhead but provides absolute isolation.", 
     "Tech"),
    ("Setting up CI/CD pipelines with GitHub Actions", 
     "Automate your testing and deployment workflows using YAML.", 
     "Continuous Integration and Continuous Deployment (CI/CD) ensures that code modifications are automatically tested and built. GitHub Actions allows you to configure workflows in YAML files in your repository to run test suites on every pull request.", 
     "Tech"),
    ("Mastering SQL joins and database indexes", 
     "Optimize your database queries using indexation and proper joins.", 
     "Database performance depends heavily on indexing. An index allows the database engine to find rows quickly without scanning the whole table. Proper usage of INNER JOIN, LEFT JOIN, and index constraints can speed up queries by a factor of 100.", 
     "Tech"),
    ("An introduction to TypeScript for JavaScript developers", 
     "Add static typing to your JS code to catch bugs early in development.", 
     "TypeScript is a typed superset of JavaScript that compiles to plain JavaScript. It adds static types, interfaces, and namespaces, allowing editors to provide autocomplete and catch errors before running the code in the browser.", 
     "Tech"),
    ("Building real-time web apps with WebSockets", 
     "Learn how to implement bi-directional communication between client and server.", 
     "WebSockets provide a persistent connection between the client and server. This allows real-time data push (like chat messages or live dashboards) without the overhead of HTTP polling. Django Channels and Socket.io are popular choices.", 
     "Tech"),
    ("Optimizing Node.js performance and memory leaks", 
     "Diagnose and resolve performance bottlenecks in backend JavaScript.", 
     "Node.js runs on the V8 engine and uses an event loop for asynchronous I/O. Memory leaks can occur due to global variables, active timers, or closures retaining references. Profiling tools can help inspect heap dumps and CPU usage.", 
     "Tech"),

    # DESIGN
    ("The ultimate guide to UI/UX design principles", 
     "Discover the core principles of modern user interface and user experience design.", 
     "Good design is invisible. It focuses on usability, accessibility, and visual hierarchy. By applying principles like contrast, proximity, alignment, and whitespace, you can guide users naturally through your application and reduce cognitive load.", 
     "Design"),
    ("How to choose the perfect color palette for your website", 
     "A scientific approach to selecting colors that match your brand identity.", 
     "Color theory plays a huge role in web design. You should select a primary color, a secondary color, and a high-contrast accent color. Keep accessibility in mind by ensuring a contrast ratio of at least 4.5:1 for body text (WCAG AA).", 
     "Design"),
    ("Best practices for typography in web design", 
     "How font sizes, line heights, and choices affect readability.", 
     "Typography is the foundation of web interface design. Limit your project to two font families: one for headings and one for body text. Ensure a comfortable line height (typically 1.5 for body text) and use responsive font sizes.", 
     "Design"),
    ("Mastering Figma for UI prototyping and design systems", 
     "Learn how to create reusable components, auto layouts, and interactive prototypes.", 
     "Figma is the leading tool for interface designers. Using components, variants, and auto-layout features allows you to build design systems that stay consistent across your product. Prototypes help validate layouts before writing code.", 
     "Design"),
    ("Responsive layouts: mobile-first design strategies", 
     "Why designing for mobile screens first leads to cleaner code and UX.", 
     "Mobile-first design involves designing the mobile screen first, then using CSS media queries to expand the layout for tablet and desktop. This prevents desktop layouts from breaking on smaller screens and forces you to prioritize content.", 
     "Design"),
    ("The power of whitespace in modern web interfaces", 
     "Learn how blank spaces can improve readability and look premium.", 
     "Whitespace (or negative space) is not empty space; it is a design element. It separates content, creates breathing room, and gives elements a premium, high-end feel. Don't crowd your pages; let your layout breathe.", 
     "Design"),
    ("Designing accessible websites for users with disabilities", 
     "How to comply with WCAG guidelines: screen readers, keyboard nav, and contrast.", 
     "Web accessibility (a11y) ensures everyone can use your site. Use semantic HTML (like nav, main, footer), add alt tags to images, ensure contrast ratios are met, and make sure all interactive elements can be focused using a keyboard.", 
     "Design"),
    ("How to create a consistent design system for your brand", 
     "A guide to style guides, UI components, and design tokens.", 
     "A design system is a single source of truth for your brand's digital identity. It includes design tokens (color variables, spacing scales, font weights) and reusable UI components. This ensures visual coherence across different apps.", 
     "Design"),
    ("Micro-interactions: details that make UI feel alive", 
     "How subtle hover effects, active states, and transitions delight users.", 
     "Micro-interactions are subtle animations that respond to user actions. For example, a button shifting up on hover, a checkmark icon spinning on success, or a input border glowing. They make the application feel premium and responsive.", 
     "Design"),
    ("Dark mode vs Light mode: UX and design guidelines", 
     "Learn how to style a dark interface without hurting readability.", 
     "Dark mode design requires more than just inverting colors. Use dark gray surfaces instead of pure black to allow subtle drop shadows. Reduce text contrast slightly (using off-white rather than pure white) to avoid eye strain in dark rooms.", 
     "Design"),

    # MARKETING
    ("SEO best practices for modern web applications", 
     "Optimize your React and Django apps to rank higher on Google search.", 
     "Search Engine Optimization (SEO) requires structured semantic HTML, fast loading speeds, meta title/description tags, and schema markup. For single-page React apps, server-side rendering (SSR) or pre-rendering is crucial for indexing.", 
     "Marketing"),
    ("How to grow your email list and build campaigns that convert", 
     "Strategies for lead magnets, opt-in forms, and automated email flows.", 
     "Email marketing remains the highest ROI marketing channel. Create valuable lead magnets (like free ebooks or templates), place clear opt-in forms on your blog, and set up automated onboarding sequences to nurture new subscribers.", 
     "Marketing"),
    ("Copywriting secrets: how to write headlines that get clicks", 
     "The psychology behind high-converting headlines and call-to-actions.", 
     "Good copywriting focuses on benefits, not features. Your headline should promise to solve a specific pain point or satisfy a curiosity. Use action verbs in your call-to-action buttons (like 'Get Started Now' instead of 'Submit').", 
     "Marketing"),
    ("Growth hacking 101: startup marketing tactics", 
     "How to acquire users quickly using viral loops, referrals, and product UX.", 
     "Growth hacking blends marketing, engineering, and product analytics. Focus on viral loops (e.g., users sharing the product to unlock features) and referral programs. Optimize the registration funnel to reduce drop-offs.", 
     "Marketing"),
    ("Analyzing user behavior using Google Analytics and hotjar", 
     "How to track user journeys, click maps, and conversion funnels.", 
     "Web analytics tell you what users do, while heatmaps show where they look and click. Setting up custom event tracking for button clicks and analyzing drop-off points in your funnel lets you make data-driven optimizations.", 
     "Marketing"),
    ("The role of content marketing in organic growth", 
     "Why writing high-quality blog articles is the best long-term traffic source.", 
     "Content marketing is the process of creating valuable, free content to attract a defined audience. By publishing in-depth articles that answer search queries, you build authority, earn backlinks, and get free organic search traffic.", 
     "Marketing"),
    ("Social media marketing strategy for developers and tech startups", 
     "Which platforms to choose and how to share technical content.", 
     "Tech startups should target platforms like Twitter/X, GitHub, LinkedIn, and dev.to. Share building-in-public updates, technical challenges, and free open-source tools to build trust within the developer community.", 
     "Marketing"),
    ("Conversion Rate Optimization (CRO) for landing pages", 
     "Simple design and copy changes that double your sales or signups.", 
     "CRO involves tweaking your landing page to increase the percentage of visitors who take action. Remove distracting navigation links, show social proof (testimonials, logos), and place a single primary call-to-action above the fold.", 
     "Marketing"),
    ("A guide to running profitable Google and Meta Ads", 
     "Learn how to target the right audience and optimize advertising spend.", 
     "Paid advertising requires careful targeting and budget management. Use Google Search ads for high-intent search queries, and Meta (Facebook/Instagram) ads for demographic and interest targeting. Always test multiple ad creatives.", 
     "Marketing"),
    ("Building a brand identity: from logo to market positioning", 
     "How to define your brand values, voice, and unique value proposition.", 
     "A strong brand identity differentiates you from competitors. Define your target audience, establish a unique tone of voice (e.g., professional, friendly, or bold), and align all visual assets with your core values.", 
     "Marketing"),

    # BUSINESS
    ("How to validate your SaaS idea before writing any code", 
     "Save time and money by confirming user demand for your software concept.", 
     "Before building a product, talk to potential customers. Create a simple landing page explaining the value proposition with a signup form. If you get enough signups, you validate interest. You can also run pre-sales to prove intent to pay.", 
     "Business"),
    ("Choosing the right monetization model for your app", 
     "Pros and cons of subscription, freemium, transactional, and ad-based models.", 
     "SaaS models rely on recurring subscriptions (monthly/annual). Freemium models attract users with free plans while charging for advanced features. Choose a model that aligns with your user value and customer acquisition cost.", 
     "Business"),
    ("How to write a pitch deck and raise venture capital", 
     "The key slides every investor wants to see in a startup presentation.", 
     "A pitch deck should cover: problem, solution, market size, product, traction, business model, competition, team, and financial ask. Keep it visual and tell a story about how your startup can become a massive company.", 
     "Business"),
    ("Project management methodologies: Agile vs Waterfall", 
     "An overview of software project delivery methods and team collaboration.", 
     "Agile methodology (Scrum, Kanban) focuses on iterative development, quick releases, and adaptability. Waterfall is sequential and planned up-front, suitable for hardware or construction projects with fixed scopes.", 
     "Business"),
    ("Key SaaS metrics you need to track: LTV, CAC, and Churn", 
     "Understanding customer lifetime value, acquisition cost, and retention.", 
     "Customer Lifetime Value (LTV) is the total revenue a customer generates. Customer Acquisition Cost (CAC) is the cost to acquire one customer. Churn rate measures the percentage of customers who cancel their subscription each month.", 
     "Business"),
    ("Client relationship management for freelance developers", 
     "How to communicate, write proposals, set boundaries, and get paid on time.", 
     "Successful freelancing requires great communication. Always write detailed project proposals with clear scopes, set milestones for payments, and document change requests to avoid scope creep and payment delays.", 
     "Business"),
    ("The Lean Startup methodology: Build, Measure, Learn", 
     "How to minimize risk by developing a Minimum Viable Product (MVP).", 
     "The Lean Startup framework prioritizes speed and learning. Build a Minimum Viable Product (MVP), launch it to early adopters, measure their usage, and learn whether to pivot (change direction) or persevere (continue building).", 
     "Business"),
    ("Understanding product-market fit and how to measure it", 
     "The Sean Ellis test and other indicators that your product matches the market.", 
     "Product-Market Fit (PMF) means being in a good market with a product that can satisfy that market. You can measure it using the Sean Ellis survey question: 'How would you feel if you could no longer use this product?'. If >40% answer 'very disappointed', you have PMF.", 
     "Business"),
    ("Negotiation skills for tech leaders and managers", 
     "How to negotiate salaries, contracts, and deadlines effectively.", 
     "Effective negotiation is about finding win-win agreements. Focus on interests rather than positions, separate the people from the problem, and use objective criteria. Always have a clear BATNA (Best Alternative to a Negotiated Agreement).", 
     "Business"),
    ("Setting up a remote company: culture, tools, and compliance", 
     "Best practices for hiring and managing teams across different timezones.", 
     "Managing a remote company requires async communication workflows, clear documentation (a company handbook), and collaboration tools like Slack, Notion, and Jira. Make sure to comply with local tax and labor laws when hiring.", 
     "Business"),
]

# Duplicate the dataset with small variations to make it larger (160 rows total)
expanded_data = []
for i in range(4):
    for title, excerpt, content, category in data:
        suffix = f" (Part {i+1})" if i > 0 else ""
        expanded_data.append((title + suffix, excerpt, content, category))

# Save to CSV
csv_path = os.path.join(os.path.dirname(__file__), "dataset.csv")
with open(csv_path, mode="w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(["title", "excerpt", "content", "category"])
    writer.writerows(expanded_data)

print(f"Generated synthetic dataset with {len(expanded_data)} rows at {csv_path}")
